#include <QDefines.h>

void DeclareQRecord(){
    QS_USR_DICTIONARY(RecordID::LOG_VERBOSE);
    QS_USR_DICTIONARY(RecordID::LOG_DEBUG);
    QS_USR_DICTIONARY(RecordID::LOG_INFO);
    QS_USR_DICTIONARY(RecordID::LOG_ERROR);
    QS_USR_DICTIONARY(RecordID::LOG_TOPIC);
    QS_USR_DICTIONARY(RecordID::LOG_WARNING);
    QS_USR_DICTIONARY(RecordID::LOG_MISC_DATA_COLLECTION);

    QS_USR_DICTIONARY(CommandID::FIXTURE_SETUP);
    QS_USR_DICTIONARY(CommandID::FIXTURE_TEARDOWN);
    QS_USR_DICTIONARY(CommandID::COMMAND_A);
    QS_USR_DICTIONARY(CommandID::COMMAND_B);
    QS_USR_DICTIONARY(CommandID::COMMAND_X);
    QS_USR_DICTIONARY(CommandID::COMMAND_Y);
    QS_USR_DICTIONARY(CommandID::COMMAND_Z);
    QS_USR_DICTIONARY(CommandID::MY_RECORD);
};